### ISSUE TITLE
Sync with latest upstream code

### ISSUE THREAD

**Issue by ghost** [junkurihara/dnscrypt-server-docker-modns#1]
@junkurihara Could you sync your modns with the latest upstream code https://github.com/jedisct1/dnscrypt-server-docker/commits/master
Seems there are patched a lot of bug fixes at Unbound 1.13.2.

I don't know what the goal is either of modns. 
Is it safe tp run it on the long term.
Do you regularly update this repo with the latest upstream code or is it just a test because of your work?

Thanks.

**Comment by junkurihara** [comment]
@bertusdebruin 

I periodically update any μODNS-related repos to track the Frank's upstream repo as long as I and other guys operate μODNS servers. However, tracking may take some time due to my private situation. Since this is a free and open source software project, you can contribute it yourself by making pull requests.
